name: platform_channel

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    path: ../../sdk/flutter/packages/flutter_driver

flutter:
  uses-material-design: true
